/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, FormWithCrudOperation } from "@prisma/client";

export class FormWithCrudOperationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.FormWithCrudOperationFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.FormWithCrudOperationFindManyArgs>
  ): Promise<number> {
    return this.prisma.formWithCrudOperation.count(args);
  }

  async findMany<T extends Prisma.FormWithCrudOperationFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.FormWithCrudOperationFindManyArgs>
  ): Promise<FormWithCrudOperation[]> {
    return this.prisma.formWithCrudOperation.findMany(args);
  }
  async findOne<T extends Prisma.FormWithCrudOperationFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.FormWithCrudOperationFindUniqueArgs>
  ): Promise<FormWithCrudOperation | null> {
    return this.prisma.formWithCrudOperation.findUnique(args);
  }
  async create<T extends Prisma.FormWithCrudOperationCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.FormWithCrudOperationCreateArgs>
  ): Promise<FormWithCrudOperation> {
    return this.prisma.formWithCrudOperation.create<T>(args);
  }
  async update<T extends Prisma.FormWithCrudOperationUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.FormWithCrudOperationUpdateArgs>
  ): Promise<FormWithCrudOperation> {
    return this.prisma.formWithCrudOperation.update<T>(args);
  }
  async delete<T extends Prisma.FormWithCrudOperationDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.FormWithCrudOperationDeleteArgs>
  ): Promise<FormWithCrudOperation> {
    return this.prisma.formWithCrudOperation.delete(args);
  }
}
