/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateFormWithCrudOperationArgs } from "./CreateFormWithCrudOperationArgs";
import { UpdateFormWithCrudOperationArgs } from "./UpdateFormWithCrudOperationArgs";
import { DeleteFormWithCrudOperationArgs } from "./DeleteFormWithCrudOperationArgs";
import { FormWithCrudOperationFindManyArgs } from "./FormWithCrudOperationFindManyArgs";
import { FormWithCrudOperationFindUniqueArgs } from "./FormWithCrudOperationFindUniqueArgs";
import { FormWithCrudOperation } from "./FormWithCrudOperation";
import { FormWithCrudOperationService } from "../formWithCrudOperation.service";

@graphql.Resolver(() => FormWithCrudOperation)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FormWithCrudOperationResolverBase {
  constructor(
    protected readonly service: FormWithCrudOperationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "FormWithCrudOperation",
    action: "read",
    possession: "any",
  })
  async _formWithCrudOperationsMeta(
    @graphql.Args() args: FormWithCrudOperationFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [FormWithCrudOperation])
  @nestAccessControl.UseRoles({
    resource: "FormWithCrudOperation",
    action: "read",
    possession: "any",
  })
  async formWithCrudOperations(
    @graphql.Args() args: FormWithCrudOperationFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FormWithCrudOperation[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "FormWithCrudOperation",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => FormWithCrudOperation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FormWithCrudOperation",
    action: "read",
    possession: "own",
  })
  async formWithCrudOperation(
    @graphql.Args() args: FormWithCrudOperationFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FormWithCrudOperation | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "FormWithCrudOperation",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => FormWithCrudOperation)
  @nestAccessControl.UseRoles({
    resource: "FormWithCrudOperation",
    action: "create",
    possession: "any",
  })
  async createFormWithCrudOperation(
    @graphql.Args() args: CreateFormWithCrudOperationArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FormWithCrudOperation> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "FormWithCrudOperation",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FormWithCrudOperation"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => FormWithCrudOperation)
  @nestAccessControl.UseRoles({
    resource: "FormWithCrudOperation",
    action: "update",
    possession: "any",
  })
  async updateFormWithCrudOperation(
    @graphql.Args() args: UpdateFormWithCrudOperationArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FormWithCrudOperation | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "FormWithCrudOperation",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FormWithCrudOperation"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FormWithCrudOperation)
  @nestAccessControl.UseRoles({
    resource: "FormWithCrudOperation",
    action: "delete",
    possession: "any",
  })
  async deleteFormWithCrudOperation(
    @graphql.Args() args: DeleteFormWithCrudOperationArgs
  ): Promise<FormWithCrudOperation | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
